
default: &default
  adapter: sqlite3
  pool: 5

development:
  <<: *default
  database: db/development.sqlite3


test:
  <<: *default
  database: db/test.sqlite3


production:
  <<: *default
  database: db/production.sqlite3
  username: rails-test
  password: <%= ENV['RAILS-TEST_DATABASE_PASSWORD'] %>
